services:
  lorndev-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: lorndev:dev
    container_name: lorndev-dev
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - ".env"
    ports:
      - "3000:3000"

    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: package.json

  lorndev-prod:
    image: ghcr.io/shencan03/lorndev:main
    container_name: lorndev-prod
    depends_on:
      cloudflare:
        condition: service_started

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    command: tunnel --no-autoupdate run
    env_file:
      - ".env.docker"
